version: '3'

services:
  bind9:
    image: ubuntu/bind9
    container_name: dns_server
    restart: always
    volumes:
      - ./config:/etc/bind
      - ./data:/var/cache/bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - dns_network

networks:
  dns_network:
    driver: bridge
